// Common
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useMemo, useState } from 'react';
// Components
import { EmailStep, PhoneStep, PersonalInfo, Success, CurpInfo } from '@components/signup';
import { Navbar, ProgressPoints } from '@components/index';
// Context
import { SignupContext } from 'context';
import toast, { Toaster } from 'react-hot-toast';

const Home: NextPage = () => {
	const [step, setStep] = useState<number>(1);

	const MultiStepForm = () => {
		switch (step) {
			case 1:
				return <EmailStep />;
			case 2:
				return <PhoneStep />;
			case 3:
				return <PersonalInfo onSubmit={(stps: number) => setStep(v => v + stps)} />;
			case 4:
				return <CurpInfo onSubmit={() => setStep(v => v + 1)} />;
			default:
				return <Success />;
		};
	}

	const CustomContextProvider = ({ children }: any) => {
		const [formGroup, setFormGroup] = useState<any>({});

		return (
			<SignupContext.Provider
				value={useMemo(() => ({ step, setStep, formGroup, setFormGroup, toast }), [
					formGroup, setFormGroup
				])}>
				{children}
			</SignupContext.Provider>
		);
	}

	return (
		<>
			<Head>
				<title>100 Ladrillos | Sign up</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Toaster position="bottom-center" />
			<div className="bg-white w-screen h-screen lg:h-[calc(100vh-72px)] overflow-hidden sm:overflow-visible">
				<Navbar className="fixed lg:relative z-10" />
				<CustomContextProvider>
					<div className="flex flex-col lg:flex-row h-full">
						<div className="flex lg:max-w-[524px] h-full z-0 bg-red-500	">
							<Image src="/assets/img/Background-img-angel.webp" priority
								alt="100 Ladrillos logotipo" width={1572} height={1809}
								objectFit="cover" />
						</div>
						<div className="main-container">
							<div className="w-full">
								<div className="sub-container">
									<MultiStepForm />
									<ProgressPoints />
								</div>
							</div>
						</div>
					</div>
				</CustomContextProvider>
			</div>
		</>
	);
}

export async function getStaticProps() {
	return {
		props: {},
	};
}

export default Home;
